name: Update M3U Logos

# Habilitar permisos de escritura para que el bot pueda hacer push
permissions:
  contents: write

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'playlists/**/*.m3u'

jobs:
  fetch-logos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Por defecto persiste credenciales, permite usar GITHUB_TOKEN
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tmdbv3api pyyaml

      - name: Fetch and inject logos
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python scripts/fetch_logos.py playlists/your_playlist.m3u

      - name: Commit updated playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlists/your_playlist.m3u
          git diff-index --quiet HEAD || git commit -m "chore: update M3U logos"
          git push
